;;; This file was automatically generated by the sunterlib
;;; makefile, so do not edit it.

;;; This file is part of the Scheme Untergrund Library. For copyright
;;; information, see the file COPYING which comes with the
;;; distribution.

(define license
  "
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
3. The name of the authors may not be used to endorse or promote products
   derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE AUTHORS ``AS IS'' AND ANY EXPRESS OR
IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
")

;(define port->string
;  (lambda (port)
;    (let loop ((result ""))
;      (let ((chunk (read-string 1024 port)))
;        (if chunk
;            (loop (string-append result chunk))
;            result)))))

(define get-copyrights
  (lambda ()
    (call-with-input-file
        "AUTHORS"
      (lambda (port)
        (port->string port)))))

(define COPYING
  (lambda ()
    (string-append (get-copyrights) license)))

(define-package "sunterlib"
  (0 9)
  ()
  (install-file "COPYING" 'doc)
  (install-file "DETAILS" 'doc)
  (install-file "NEWS" 'doc)
  (install-file "README" 'doc)
  (install-file "README.contrib" 'doc))


;;; S48 LIBRARIES
;
;(load-package-in "s48/srfi-10")
;(load-package-in "s48/continuation-data-type")
;(load-package-in "s48/args-fold")
;(load-package-in "s48/hawk-dns-server")
;(load-package-in "s48/module-system")
;(load-package-in "s48/krims")
;(load-package-in "s48/binary-parse")
;(load-package-in "s48/cml")
;(load-package-in "s48/meta-gc")
;(load-package-in "s48/banana")
;(load-package-in "s48/exceptions")
;(load-package-in "s48/heap-images")
;(load-package-in "s48/procedure-tables")
;(load-package-in "s48/profile")
;(load-package-in "s48/riatables")
;(load-package-in "s48/concurrency")
;(load-package-in "s48/intsets")
;(load-package-in "s48/cavespider")
;
; SCSH LIBRARIES

(load-package-in "scsh/tiff")
(load-package-in "scsh/CSAN")
(load-package-in "scsh/base64")
(load-package-in "scsh/interaction")
(load-package-in "scsh/bytio")
(load-package-in "scsh/dir-streams")
(load-package-in "scsh/file-mode")
(load-package-in "scsh/scgame")
(load-package-in "scsh/twentyseventree")
(load-package-in "scsh/sequences")
(load-package-in "scsh/thttpd")
(load-package-in "scsh/scganadu")
(load-package-in "scsh/scratch")
(load-package-in "scsh/snow")
(load-package-in "scsh/afs")
(load-package-in "scsh/tmail")
(load-package-in "scsh/pps")
(load-package-in "scsh/encryption")
(load-package-in "scsh/schemedoc")
(load-package-in "scsh/treaps")
(load-package-in "scsh/image-info")
